# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mixedMomentsC <- function(y, mixedOnly = FALSE) {
    .Call(`_functionalCovariance_mixedMomentsC`, y, mixedOnly)
}

splineMatrixC <- function(lower, upper, order, nbreaks, x) {
    .Call(`_functionalCovariance_splineMatrixC`, lower, upper, order, nbreaks, x)
}

penaltyMatrixC <- function(X, nzero) {
    .Call(`_functionalCovariance_penaltyMatrixC`, X, nzero)
}

singleDesignMatrixC <- function(dM, nnzero, mixedOnly = FALSE) {
    .Call(`_functionalCovariance_singleDesignMatrixC`, dM, nnzero, mixedOnly)
}

fullDesignC <- function(indexes, values, lower, upper, nbasis, order, weights, mixedOnly = FALSE) {
    .Call(`_functionalCovariance_fullDesignC`, indexes, values, lower, upper, nbasis, order, weights, mixedOnly)
}

estimateCoefficientsC <- function(fullDesign, penalty, lambda) {
    .Call(`_functionalCovariance_estimateCoefficientsC`, fullDesign, penalty, lambda)
}

takahashiDavisC <- function(L) {
    .Call(`_functionalCovariance_takahashiDavisC`, L)
}

computePredC <- function(dM, beta, mixedOnly = FALSE) {
    .Call(`_functionalCovariance_computePredC`, dM, beta, mixedOnly)
}

computeSSEC <- function(indexes, values, lower, upper, nbasis, order, beta, weights, mixedOnly = FALSE) {
    .Call(`_functionalCovariance_computeSSEC`, indexes, values, lower, upper, nbasis, order, beta, weights, mixedOnly)
}

generalizedCrossValidationC <- function(lambda, indexes, values, lower_int, upper_int, nbasis, order, designX, designY, penalty, multiplier, weights, mixedOnly = FALSE) {
    .Call(`_functionalCovariance_generalizedCrossValidationC`, lambda, indexes, values, lower_int, upper_int, nbasis, order, designX, designY, penalty, multiplier, weights, mixedOnly)
}

mixedMomentsCrC <- function(x, y) {
    .Call(`_functionalCovariance_mixedMomentsCrC`, x, y)
}

splineMatrixCrC <- function(lower, upper, order, nbreaks, x) {
    .Call(`_functionalCovariance_splineMatrixCrC`, lower, upper, order, nbreaks, x)
}

singleDesignMatrixCrC <- function(dM1, dM2) {
    .Call(`_functionalCovariance_singleDesignMatrixCrC`, dM1, dM2)
}

penaltyMatrixCrC <- function(X, Y) {
    .Call(`_functionalCovariance_penaltyMatrixCrC`, X, Y)
}

fullDesignCrC <- function(indexes1, values1, indexes2, values2, intv1, intv2, nbasis, order, weights) {
    .Call(`_functionalCovariance_fullDesignCrC`, indexes1, values1, indexes2, values2, intv1, intv2, nbasis, order, weights)
}

estimateCoefficientsCrC <- function(fullDesign, penalty, lambda) {
    .Call(`_functionalCovariance_estimateCoefficientsCrC`, fullDesign, penalty, lambda)
}

takahashiDavisCrC <- function(L) {
    .Call(`_functionalCovariance_takahashiDavisCrC`, L)
}

computeSSECrC <- function(indexes1, values1, indexes2, values2, intv1, intv2, nbasis, order, beta, weights) {
    .Call(`_functionalCovariance_computeSSECrC`, indexes1, values1, indexes2, values2, intv1, intv2, nbasis, order, beta, weights)
}

generalizedCrossValidationCrC <- function(lambda, indexes1, values1, indexes2, values2, intv1, intv2, nbasis, order, designX, designY, penalty, multiplier, weights) {
    .Call(`_functionalCovariance_generalizedCrossValidationCrC`, lambda, indexes1, values1, indexes2, values2, intv1, intv2, nbasis, order, designX, designY, penalty, multiplier, weights)
}

